services:
  mobility-metrics:
    image: mobility-metrics
    build: .
    stdin_open: true
    links:
      - conflator:conflator
    depends_on:
      - conflator
    volumes:
      - C:\Users\bscholer\Documents\Projects\mobility-metrics\data:/data
#      - C:\Users\bscholer\Documents\Projects\mobility-metrics\cache:/cache

  conflator:
    image: mobility-metrics-conflator
    build: ../mobility-metrics-conflator/
    env_file: ../mobility-metrics-conflator/.env
    volumes:
      - C:\Users\bscholer\Documents\Projects\mobility-metrics-conflator\data:/data
      - C:\Users\bscholer\Documents\Projects\mobility-metrics-conflator\cache:/cache
